baseURL = 'https://www.raveen.ca/'
languageCode = 'en-us'
title = 'Raveen.ca'
theme = ['smol', 'hugo-shortcode-gallery']

# Parameters
[params]
    subtitle = "My piece of the internet!"
    dateFmt = "02.01.2006 15:04"

# Header
[menu]
  [[menu.main]]
        identifier = "posts"
        name = "Posts"
        url = "/posts/"
        weight = 2 

  [[menu.main]]
        identifier = "categories"
        name = "Categories"
        url = "/categories/"
        weight = 4

  [[menu.main]]
        identifier = "tags"
        name = "Tags"
        url = "/tags/"
        weight = 5

  [[menu.main]]
        identifier = "about"
        name = "About"
        url = "/about/"
        weight = 1

  [[menu.main]]
        identifier = "gallery"
        name = "Gallery"
        url = "/gallery/"
        weight = 3

# Footer
  [[menu.footer]]
        identifier = "sitemap"
        name = "Sitemap & Changelog"
        url = "/sitemap/"
        weight = 1
  [[menu.footer]]
        identifier = "guestbook"
        name = "Guestbook"
        url = "/guestbook/"
        weight = 2

timeout = 60000

