baseURL = 'https://example.org/'
languageCode = 'en-us'
title = 'Raveen.ca'
theme = ["hugo-shortcode-gallery"]

[params]
      name = "Raveen"
      DateForm = "2006-12-01"
  [params.author]
    email = 'raveen@test.ca'
    name = 'Raveen'

copyright = '© 2026 Raveen'

# Header
[menu]
  [[menu.main]]
        identifier = "posts"
        name = "Posts"
        url = "/posts/"
        weight = 4 

  [[menu.main]]
        identifier = "tags"
        name = "Tags"
        url = "/tags/"
        weight = 5

  [[menu.main]]
        identifier = "about"
        name = "About"
        url = "/about/"
        weight = 1

  [[menu.main]]
        identifier = "gallery"
        name = "Gallery"
        url = "/gallery/"
        weight = 3
  [[menu.main]]
        identifier = "projects"
        name = "Projects"
        url = "/projects/"
        weight = 2     

[outputs]
      home = ['html']
      section = ['html', 'rss']
      taxonomy = ['html']
      term = ['html']

